language: node_js

node_js:
   - "4"

before_script:
  - npm -q install
  - npm -q install -g testem
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - ./testem -l Firefox,PhantomJS
